### ISSUE TITLE
Should we use a monorepo?

### ISSUE THREAD

**Issue by benjaminkay93** [NaSTAuk/graphics#1]
# Issue

Should we set this up as a monorepo, to store all components, admin and client serving and allowing this to be easily developed and used?

**Comment by moschopsuk** [comment]
So, is the plan to use something like Lerna or Yarn Workspaces?

Will people want to publish their "components", or will everything be located in a single place?

I would learn towards a mono-repo initially as it may make development easier(?), and discovery rather than it fragmented across different repos.

**Comment by benjaminkay93** [comment]
yeah, I've used yarn workspaces and when asking about lerna apparently there where issues? ill do some research on the matter, but the idea would be to improve accessibility and discoverability, and make it easier to maintain depending on test approach as things are easily tested against things in a monorepo, however it could be over kill?

**Comment by benjaminkay93** [comment]
I'm gonna spike out a monorepo on a PR, ill reference this when I get there :P

**Comment by niklasR** [comment]
Do you have any ideas on architecture? If it's a monolith, anything but a monorepo doesn't make sense either way, nullifying the question.

**Comment by benjaminkay93** [comment]
Well, I'm currently taking inspiration from projects like babel, it gives us an easy way to consistently run the same linting and testing rules as well as integration tests if we get that far. Plus enabling synchronous deployment of code will be handy. An initial mockup for the internal archecture is on the spike in #14, feel free to view at your pleasure :) 

Also, Hi Nik :D

**Comment by benjaminkay93** [comment]
So with the merger of #17 I'm gonna close this. Anyone is welcome to reopen if they want to challenge the code being in a monorepo decision 😄. No decision is ever final!
